version: '3.8'

services:
  app:
    image: bank-dev-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PGHOST=database
      - PGPORT=5432
      - PGDATABASE=bank_dev
      - PGUSER=bank_dev_user
      - PGPASSWORD=bank_dev_password

  database:
    image: postgres:15
    environment:
      - POSTGRES_DB=bank_dev
      - POSTGRES_USER=bank_dev_user
      - POSTGRES_PASSWORD=bank_dev_password
    ports:
      - "5432:5432"
